### PR TITLE
Testing the merge: Attempt 1/N

### PR DESCRIPTION
**Pull request by vkostyukov**
We're testing to see how easy it is to merge finagle-postgres in.

### CODE REVIEW

**Comment by vkostyukov** [comment]
@jeremyrsmith
@clhodapp
@jilen
@ben-healthforge
@afine
@leonmaia
@andrerigon
@dangerousben
@crispywalrus
@plaflamme
@juliano

Folks, do you mind signing the CLA? We require all Finagle contributors to sign it.

**Comment by plaflamme** [comment]
FWIW: I have a different (and more modern) implementation of Postgres on finagle [here](https://github.com/plaflamme/finagle-postgresql). It's closer to the existing mysql client, so perhaps a better candidate for merging into finagle mainline. It's unfortunately incomplete yet: lacking transactions and a proper `Cursor` implementation like finagle-mysql client has. I'm happy to help investigate the feasibility of using this alternate implementation.

**Comment by steveniemitz** [comment]
opened a new PR #908 for try 2 on this w/ finagle-postgresql.

**Comment by bryce-anderson** [comment]
This has been merged.

**Pull request closed without merging**
