### PR TITLE
fixing typo

### PR DESCRIPTION
**Pull request by gokyo**

### CODE REVIEW

**Review by tigerlily-he — APPROVED** [review]
Thanks for submitting a PR to fix this typo!

**Comment by tigerlily-he** [comment]
Hi @gokyo, Can you sign the Contributor License Agreement (CLA)? We need this before we can merge your PR. Thanks!

**Comment by tigerlily-he** [comment]
Hi @gokyo, Please sign the Contributor License Agreement (CLA) if you're interested in getting this PR merged. Thank you!

**Comment by bryce-anderson** [comment]
Hi @gokyo, can you please sign the CLA? Otherwise we cannot accept this PR.

**Comment by tigerlily-he** [comment]
@gokyo, I'm closing this PR. We cannot accept contributions without a CLA. Please re-open it when you sign the CLA. Thank you!

**Pull request closed without merging**
