### PR TITLE
finagle-redis: Enable running integration tests in finagle-redis.

### PR DESCRIPTION
**Pull request by mkhq**
Problem

Unit tests and integration tests are mixed in the finagle-redis project
under the test path. In addition, the SBT configuration is only running
unit tests. This partially solves issue #360.

Solution

Moved the integration test files to the  path from . Extracted traits
used for integration tests and created a new file in the  path. Added
configuration for IntegrationTest in the finagle-redis project.

A summary of the changes adopted from PR https://github.com/twitter/finagle/pull/400:
- Run integration tests using `it:test`
- Tested using Redis 3.2
- Removed btree and topology tests since this is not part of the official release
- Fixed scans by replacing PATTERN with MATCH
- Updated the expected DUMP results, seems this differs between versions.
- Fixed a bug when running sentinel tests, not all servers shutdown correctly
- Fixed sentinel protocol to use link-pending-commands instead of pending-commands

Result

Running 'test' only executes unit tests. Running 'it:test' executes the
integration tests.

### CODE REVIEW

**Comment by mkhq** [comment]
Ping @mosesn

**Comment by nepthar** [comment]
I've attempted to pull this in internally, but finagle-redis has moved quite a bit. Would you mind rebasing your changes on the latest in develop? After that, I'll make sure this gets in asap.

**Comment by mkhq** [comment]
@nepthar sure, ill rebase and will also check your earlier comment, thanks!

**Comment by luliu** [comment]
Hello, just wondering what the status of this PR is.  Would love to get the PATTERN -> MATCH fix.  Thanks :)

**Comment by nepthar** [comment]
@mkhq Have you had the chance to bring this up to date?

**Comment by mkhq** [comment]
@nepthar @luliu Hey, it was more than I expected so didnt finish yet. Does it make sense to make a separate PR for the PATTERN -> MATCH fix?

**Comment by luliu** [comment]
@mkhq I'll refrain from butting into your process.  :)  As long as it is still being worked on, I'm happy with a "it's done when it's done".

**Comment by nepthar** [comment]
@mkhq I always have a preference for smaller, more focused PRs, so that sounds great to me!

**Comment by mkhq** [comment]
@nepthar @luliu Added a new PR #587 that replaces PATTERN with MATCH. Tested against redis 3.2.6.

**Comment by mosesn** [comment]
Looks like this PR was subsumed by #587, will close this one.  Thanks again @mkhq!

**Comment by mosesn** [comment]
Wait a second, this one was about integration tests . . . reopening.

**Comment by mosesn** [comment]
@mkhq have you had a chance to take another look at this?

**Comment by mkhq** [comment]
@mosesn will open a new PR, this code is too outdated

**Pull request closed without merging**
