### PR TITLE
Add FOLIO to adopters

### PR DESCRIPTION
**Pull request by h-ikio**
Almost all of backend microservices at FOLIO are built using Finagle(Finatra) and communicate using Thrift protocol.

### CODE REVIEW

**Comment by iwag** [comment]
Welcome to finagle🎉💐

**Comment by cacoco** [comment]
@h-ikio would you like to also add yourself to the Finatra ADOPTERS? https://github.com/twitter/finatra/blob/develop/ADOPTERS.md. Thanks!

**Comment by vkostyukov** [comment]
Hey, I'm pulling this internally.

**Comment by vkostyukov** [comment]
Merged in 6fc2de054ed4090d8b070ab36e92a32e44f60ac7.

**Pull request closed without merging**
