### PR TITLE
Updated list of adopters with Attendify

### PR DESCRIPTION
**Pull request by kachayev**
* keeping alphabetical order

* link to the main page (there is no appropriate blog post just now)

### CODE REVIEW

**Comment by mosesn** [comment]
LGTM!  What do you use finagle for?

**Comment by kachayev** [comment]
@mosesn Just now 4 services are written in Scala/Finagle (and growing): calendars sharing, ACL, load balancer for numerous internal API endpoints, backend for developers portal and public API

**Comment by travisbrown** [comment]
I'm pulling this internally—thanks @kachayev!

**Comment by travisbrown** [comment]
Now [on GitHub](https://github.com/twitter/finagle/commit/46320e1722a9d027e5ed49fc39e9820fc2f3f9bb)—thanks!

**Pull request closed without merging**
