### PR TITLE
Add Dwango to adopters

### PR DESCRIPTION
**Pull request by iwag**
🙋

### CODE REVIEW

**Comment by mosesn** [comment]
Welcome!  Do you mind if I ask how you use finagle?

**Comment by iwag** [comment]
Sure!
Our team develop search system in our video streaming platform and use finagle for its JSON API server. 
We have more than 20 API endpoints. The APIs are almost same but have slightly different specifications :weary: Filter and service of finagle are fitted so much for us.  We implement the APIs using filter/service like combining the blocks.

As far as I know our company has the most number of Scala engineers/codes in Japan. but most of the teams use Play Framework :stuck_out_tongue:
And I heard other one team in our company is developing something using finagle!

**Comment by mosesn** [comment]
Great, I'm so glad the model is useful for you!

**Comment by iwag** [comment]
further details https://speakerdeck.com/iwag/rewrite-in-finagle 
sorry I have only Japanese slides

**Comment by mosesn** [comment]
This was merged to develop here: https://github.com/twitter/finagle/commit/330acc5245c7e627066d60b75aba1f536093df4f thanks so much!

**Pull request closed without merging**
