### PR TITLE
Add new SortedSet Commands from redis 5

### PR DESCRIPTION
**Pull request by martinffx**
### Problem
I want to use the new SortedSet commands in Redis 5

### Solution
Add new Commands to `SortedSetCommands`

### CODE REVIEW

**Comment by luciferous** [comment]
Looks good. How are we testing this?

**Comment by martinffx** [comment]
manually from the sbt console and Redis running in docker

**Comment by luciferous** [comment]
Good enough for me. Do we usually add docs when we add new commands?

**Comment by luciferous** [comment]
Just took a look and seems like nah. OK, I'll get one more person to look at this and then I'll merge it internally.

**Comment by luciferous** [comment]
Hi @martinffx, @ryanoneill pointed out that we have a [test suite for SortedSet](https://github.com/twitter/finagle/blob/develop/finagle-redis/src/test/scala/com/twitter/finagle/redis/commands/sorted-set/SortedSetCodecSuite.scala) commands. Could these new commands be added there?

**Comment by martinffx** [comment]
Yeah, I'm not so familiar with scala check and am having trouble generating an `Option[JLong]`

```
  def genOptionalJLong: Gen[Option[JLong]] =
    for {
      i <- Gen.choose(-1000L, 1000L)
      o <- Gen.oneOf(Option(new JLong(i)))
    } yield 0

  implicit val arbitraryOptionJLong: Arbitrary[Option[JLong]] = Arbitrary(genOptionalJLong)

  def checkSingleKeyOptionCount(c: String, f: (Buf, Option[JLong]) => Command): Unit = {
    forAll { (key: Buf, count: Option[JLong]) =>
      assert(
        encodeCommand(f(key, count)) == c.split(" ").toSeq ++ Seq(key.asString, count)
      )
    }

    intercept[ClientError](encodeCommand(f(Buf.Empty, None)))
    intercept[ClientError](encodeCommand(f(Buf.Utf8("x"), None)))
  }

  test("ZPOPMIN", CodecTest) {
    checkSingleKeyOptionCount("ZPOPMIN", ZPopMin.apply)
  }

  test("ZPOPMAX", CodecTest) {
    checkSingleKeyOptionCount("ZPOPMAX", ZPopMax.apply)
  }
```

**Comment by martinffx** [comment]
Okay I think I figured it out.

**Comment by luciferous** [comment]
Merged in 2042c6ee63d08deb4504ad5bf70bb659c26aa483.

**Pull request closed without merging**
