### PR TITLE
Added ING Bank as adopter of Finagle.

### PR DESCRIPTION
**Pull request by spockz**
Problem

ING Bank was missing as adopter.

Solution

Added ING Bank to the README and ADOPTERS files.

Result

ING Bank is in the list of adopters.

### CODE REVIEW

**Comment by travisbrown** [comment]
Looks good to me, @spockz, but do you mind alphabetizing?

(Also for future reference, you don't necessarily need the full three-section commit message for self-explanatory additions like this.)

**Comment by spockz** [comment]
@travisbrown: done and noted. :)

**Comment by travisbrown** [comment]
Sorry about the delay, @spockz—I've just pulled this in to be merged.

**Comment by travisbrown** [comment]
Merged in 167d9a3e4c0903d8fb3d6f84487a1c5a0bb50d45. Thanks @spockz!

**Pull request closed without merging**
