### PR TITLE
sbt 1.0.4

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by kevinoliver** [comment]
cc @mosesn

**Comment by mosesn** [comment]
@sullis is there an sbt 1.0.4 feature you'd like to use?  we prefer to keep our sbt versions in sync, so if there isn't anything you need, we might not want to upgrade this immediately.

**Comment by sullis** [comment]
SBT 1.0.4 fixes a performance issue in SBT 1.0.3
https://developer.lightbend.com/blog/2017-11-27-sbt-1-0-4-hotfix-and-performance-fixes/

**Comment by cacoco** [comment]
@sullis sbt 1.0.4 introduces a scala compilation regression that fails for one of our other projects ([Scrooge](https://github.com/twitter/scrooge)). The regression was patched in 1.0.3 but looks like they didn't apply it to 1.0.4 before releasing. 

This is the issue: https://github.com/sbt/zinc/issues/127

**Comment by sullis** [comment]
obsolete

**Pull request closed without merging**
