### PR TITLE
Upgrade jackson libraries to 2.12.1

### PR DESCRIPTION
**Pull request by SerCeMan**
Reference: https://github.com/twitter/finagle/issues/885

FasterXML has recently version released jackson [version 2.12.0](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.12) libraries, the dependency can be upgraded.

### CODE REVIEW

**Comment by yufangong** [comment]
Thank you for the update! 
We would like to keep all of our libs on the same version, those are:
util/build.sbt
finagle/build.sbt
twitter-server/build.sbt
finatra/build.sbt

~~Can you make this PR cover all of those? thanks!~~ 

Edit: sorry, I think the ask was impractical, to making a PR across repos. We have an internal ticket scheduled to upgrade the version all across, ty!

**Comment by yufangong** [comment]
Unfortunately, We have run into a high-risk issue in the internal source: https://github.com/FasterXML/jackson-module-scala/issues/495.
I'm afraid we need to wait until a fix before trying to bump up, the deprecation of ScalaObjectMapper in the patched release is also concerning, so the version update won't be a quick and easy one this time.

**Comment by SerCeMan** [comment]
Thanks for the update!

**Comment by SerCeMan** [comment]
Thanks for the update! Just to clarify, would the above issue cause issues if finagle gets Jackson 2.12 as a transitive dependency? Or is the issue with one of the downstream consumers of Finagle and not Finagle itself?

**Comment by yufangong** [comment]
Thank you for bringing this up to let it falls on our radar, @SerCeMan. I believe the concern is more for the customers, especially Finatra customers as it provides default JSON [serde](https://twitter.github.io/finatra/user-guide/json/index.html). Not only we want to keep the ecosystem on the same versions but also the issue is hard to catch without thoroughly detecting this kind of use case: serialize fields in traits and objects vs serialize fields in classes.

**Comment by SerCeMan** [comment]
Hey, @yufangong! I'm just checking if the upgrade was unblocked. If I understand correctly, the referenced issue was closed. :)

**Comment by yufangong** [comment]
@SerCeMan thanks so much for the reminder! We will take give it another try shortly.

**Comment by SerCeMan** [comment]
Hey, @yufangong! I'm wondering if there were any new issues with the attempt, I noticed that Jackson is moving to developing the new 2.13 branch now, https://github.com/FasterXML/jackson#active-developed-jackson-2x-branches :)

**Comment by tigerlily-he** [comment]
Hi @SerCeMan, I work with Yufan at Twitter. Thanks for checking in! We're planning to upgrade Jackson in September and we'll look into Jackson 2.12 and 2.13.

**Comment by mosesn** [comment]
@SerCeMan update on this: we upgraded to 2.13.0 https://github.com/twitter/finagle/commit/b79b1d7e374f275e114b58d67d6e72273b97137c before discovering a [regression](https://github.com/FasterXML/jackson-databind/issues/3308) that doubled the cost of serialization in jackson-databind.  We're going to roll back for now, and will roll forward once they release 2.13.1.

**Comment by SerCeMan** [comment]
Hey, @mosesn! Thank you for the update!

**Comment by tigerlily-he** [comment]
Hi @SerCeMan, The January 2022 release of Finagle has the Jackson upgrade to 2.13.1. https://github.com/twitter/finagle/commit/831b25120addc828b7de83ae20dfbc7c2606125a. 

Thank you for following this journey on the Jackson upgrade! I will close this PR now.

**Comment by SerCeMan** [comment]
@tigerlily-he That's awesome, thanks 🎉

**Pull request closed without merging**
