### PR TITLE
fix broken WatermarkPool link in doc, also add *.pyc to .gitignore

### PR DESCRIPTION
**Pull request by xudifsd**
fix broken link in doc
also add *.pyc to .gitignore to avoid accidentally git add

### CODE REVIEW

**Comment by mosesn** [comment]
LGTM

**Comment by stevegury** [comment]
LGTM

**Comment by blackicewei** [comment]
I merged this.

**Comment by dschobel** [comment]
merged in https://github.com/twitter/finagle/commit/cce4c90a88e1d95e17749a642fafda109bfb305a

**Pull request closed without merging**
