### PR TITLE
Added test-case for configuring Thrift over TLS via stack param

### PR DESCRIPTION
**Pull request by suls**
Problem

#412 fixed the netty-pipeline for Thirft but didn't add a test.

Solution

Added end-to-end test-case for Thrift/TLS for stack based client and server.

Result

Green ;)

--

Please let me know your opinion about the `src/test/resources` folder including the certificate and key in particular. Happy to adjust based on your feedback!

Cheers, Mathias

### CODE REVIEW

**Comment by kevinoliver** [comment]
thanks. i'll get this pulled this in locally. fwiw, i probably need to modify the patch so that our pants build system knows about this resource, but it should be a minor change and you'll get full credit for the patch.

**Comment by kevinoliver** [comment]
Ok, well even with sbt this test fails locally for me:

```
[info] *** 1 TEST FAILED ***
[error] Failed: Total 182, Failed 1, Errors 0, Passed 181
[error] Failed tests:
[error] 	com.twitter.finagle.thrift.EndToEndTest
[error] (finagle-thrift/test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 10 s, completed Sep 14, 2015 10:20:31 AM
> Sep 14, 2015 10:20:32 AM org.jboss.netty.channel.socket.nio.AbstractNioSelector
WARNING: Failed to initialize an accepted socket.
java.lang.IllegalArgumentException: requirement failed: Failed to run command 'openssl pkcs12 -export -password pass:FKWBQLFWRKIUTHSLSOXMEVIX -in /var/folders/7m/zdymhkzn7tqb798sk_ld6mjc0000gn/T/temp8021341077388431901dir/FKWBQLFWRKIU.pem -out /var/folders/7m/zdymhkzn7tqb798sk_ld6mjc0000gn/T/temp8021341077388431901dir/FKWBQLFWRKIU.p12'
	at scala.Predef$.require(Predef.scala:233)
	at com.twitter.finagle.ssl.Shell$.run(Util.scala:7)
	at com.twitter.finagle.ssl.PEMEncodedKeyManager$.makeKeystore(PEMEncodedKeyManager.scala:79)
	at com.twitter.finagle.ssl.PEMEncodedKeyManager$.apply(PEMEncodedKeyManager.scala:30)
	at com.twitter.finagle.ssl.JSSE$.com$twitter$finagle$ssl$JSSE$$makeContext$1(JSSE.scala:42)
	at com.twitter.finagle.ssl.JSSE$$anonfun$1.apply(JSSE.scala:59)
	at com.twitter.finagle.ssl.JSSE$$anonfun$1.apply(JSSE.scala:59)
	at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:189)
	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:91)
	at com.twitter.finagle.ssl.JSSE$.server(JSSE.scala:57)
	at com.twitter.finagle.ssl.Ssl$$anonfun$server$1.apply(Ssl.scala:49)
	at com.twitter.finagle.ssl.Ssl$$anonfun$server$1.apply(Ssl.scala:45)
	at scala.Option.getOrElse(Option.scala:120)
	at com.twitter.finagle.ssl.Ssl$.server(Ssl.scala:45)
	at com.twitter.finagle.thrift.EndToEndTest$$anonfun$17$$anonfun$mkThriftTlsServer$1$1.apply(EndToEndTest.scala:292)
	at com.twitter.finagle.thrift.EndToEndTest$$anonfun$17$$anonfun$mkThriftTlsServer$1$1.apply(EndToEndTest.scala:292)
	at com.twitter.finagle.netty3.Netty3Listener$.addTlsToPipeline(Netty3Listener.scala:101)
	at com.twitter.finagle.netty3.Netty3Listener$$anon$4$$anonfun$getPipeline$3.apply(Netty3Listener.scala:302)
	at com.twitter.finagle.netty3.Netty3Listener$$anon$4$$anonfun$getPipeline$3.apply(Netty3Listener.scala:301)
	at scala.Option$WithFilter.foreach(Option.scala:208)
	at com.twitter.finagle.netty3.Netty3Listener$$anon$4.getPipeline(Netty3Listener.scala:301)
	at org.jboss.netty.channel.socket.nio.NioServerBoss.registerAcceptedChannel(NioServerBoss.java:134)
	at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:104)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Sep 14, 2015 10:20:33 AM org.jboss.netty.channel.socket.nio.AbstractNioSelector
WARNING: Failed to initialize an accepted socket.
java.lang.NullPointerException
	at com.twitter.finagle.thrift.EndToEndTest$$anonfun$17$SslFile$2$.<init>(EndToEndTest.scala:284)
	at com.twitter.finagle.thrift.EndToEndTest$$anonfun$17.com$twitter$finagle$thrift$EndToEndTest$$anonfun$$SslFile$1$lzycompute(EndToEndTest.scala:283)
	at com.twitter.finagle.thrift.EndToEndTest$$anonfun$17.com$twitter$finagle$thrift$EndToEndTest$$anonfun$$SslFile$1(EndToEndTest.scala:283)
	at com.twitter.finagle.thrift.EndToEndTest$$anonfun$17$$anonfun$mkThriftTlsServer$1$1.apply(EndToEndTest.scala:292)
	at com.twitter.finagle.thrift.EndToEndTest$$anonfun$17$$anonfun$mkThriftTlsServer$1$1.apply(EndToEndTest.scala:292)
	at com.twitter.finagle.netty3.Netty3Listener$.addTlsToPipeline(Netty3Listener.scala:101)
	at com.twitter.finagle.netty3.Netty3Listener$$anon$4$$anonfun$getPipeline$3.apply(Netty3Listener.scala:302)
	at com.twitter.finagle.netty3.Netty3Listener$$anon$4$$anonfun$getPipeline$3.apply(Netty3Listener.scala:301)
	at scala.Option$WithFilter.foreach(Option.scala:208)
	at com.twitter.finagle.netty3.Netty3Listener$$anon$4.getPipeline(Netty3Listener.scala:301)
	at org.jboss.netty.channel.socket.nio.NioServerBoss.registerAcceptedChannel(NioServerBoss.java:134)
	at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:104)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by suls** [comment]
Hi @kevinoliver - and thanks for checking!
As you can see in 9464bca43ad8b84a129767d018a58391b4ed74c6 I managed squeeze an additional character in the certificate .. :walking:

With eaf64a746ec43e542c4ba330d1db8f836a0a901c I tried to make the test a bit less brittle - `StatsReceiver` seems to not report a success sometimes when using the `someway` method ..

**Comment by kevinoliver** [comment]
thanks! don't think i'd've figured that one out...

i'm a bit bogged down right now, but hopefully i can get back to this by the end of the week.

**Comment by kevinoliver** [comment]
Ok this is merged in. Should show up on the develop branch on Monday.

Thanks again!

**Pull request closed without merging**
