### PR TITLE
ugh how is anyone supposed to even understand finagle?!!!

### PR DESCRIPTION
**Pull request by olix0r**
# PROBLEM:
    
I was trying to use Finagle but I had to keep looking at a dictionary because Finagle kept using this word "Request" and I don't know what it means.  This makes it virtually impossible for new programmers to get involved in Finagle.  I feel like Twitter did this specifically to discourage me from understanding Finagle.
    
# SOLUTION:
    
Replace all instances of 'Request' with 'Ask'.
    
# RESULT:
    
Finagle is now *much* easier to understand and it MUCH easier to type things.

### CODE REVIEW

**Comment by mosesn** [comment]
LGTM, but this is a pretty big change, and I don't think we have the bandwidth to cutover everyone to use the new API.  Maybe make another module that people can depend on?  Obviously we'll need to do this for finagle-httpx also.  Maybe finagle-http-ask and finagle-httpx-ask?  That way we can slowly phase out finagle-http{,x} without causing too much trouble.

**Comment by olix0r** [comment]
@mosesn i understand your concerns but do you really think people are going to use finagle without this change?  i'd consider this a serious blocker to widespread FOSS adoption.

**Comment by bmdhacks** [comment]
This is an excellent pull-ask

**Comment by coops** [comment]
burn 1 2 dis

**Comment by nshkrob** [comment]
I'm going to wait for a green build, but shouldn't you also replace Response with Answer?

**Comment by mariusae** [comment]
This is a good start, but why stop here? I really think that the result of an Ask is a Learning, so, the type variables should be: Service[Ask, Learning]. 

This also teaches an important life lesson: an ask today equals a Future[Learning]

**Comment by olix0r** [comment]
@nshkrob perhaps ```Services[Ask, Learning]``` best captures this?

**Comment by travisbrown** [comment]
I thought we decided no punctuation on the "Problem" / "Solution" / "Result" headers in the commit message? Please consult CONTRIBUTING.md in the future @olix0r.

**Comment by vkostyukov** [comment]
@olix0r since you're here, can also replace `c.t.u.Future` with `scala.concurrent.Future`?

**Comment by sonjake** [comment]
We can take holistic approach here and synergize until we reach consensus. I'll touch base with our internal stakeholders and cycle back.

**Comment by mariusae** [comment]
@travisbrown Those headings are admittedly outdated. They probably should be named Customer ask/Business Plan/Business Case/

**Comment by softprops** [comment]
Without additional context, perhaps you can define a package level type alias

```scala
type Argument = Service[Ask, Learning]
```

For which you could derive concrete instances of Strawmen.

**Comment by teodimoff** [comment]
Guys, whats wrong with Request, Response types?

**Comment by dschobel** [comment]
@teodimoff the core issue is that "Request" / "Response" are technical jargon which are practically meaningless in the real world. I like this change since finagle shouldn't require a formal CS background to use and enjoy.

**Comment by travisbrown** [comment]
The entire Finagle team set aside today to discuss this change, and after a lot of debate we've decided to close this PR as `wont-fix`. Sorry @olix0r. If you feel the need to create a more pragmatically-focused Finagle fork, we can talk about whether the [Finagle organization](https://github.com/finagle) would be an appropriate place to host it.

**Pull request closed without merging**
