### PR TITLE
Support for Redis scripting commands #272

### PR DESCRIPTION
**Pull request by kashif**
initial attempt at #272  not working

### CODE REVIEW

**Comment by mosesn** [comment]
@kashif still happy to help if you have any further questions :+1:

**Comment by kashif** [comment]
thanks @mosesn  I have a question: how to I escape the quotes when wraping and unwraping strings?

The `EVAL` command needs a string as its script:

```
eval "return {KEYS[1],KEYS[2],ARGV[1],ARGV[2]}" 2 key1 key2 first second
```

but when parsing it, I get an error since it thinks that `"return`  is the first argument...

**Comment by mosesn** [comment]
I think there's a bug in the parser where it always delimits on ' ' instead of treating stuff between quotes specially.  I'll take a closer look.

**Comment by mosesn** [comment]
@kashif I threw together something that should be an OK first approximation.  I haven't tested it at all, so it may take some tweaking, but this patch should generally explain how to go about fixing the bug.

https://github.com/mosesn/finagle/compare/support-string-split.patch

**Comment by mosesn** [comment]
ugh ok now it should work (although it's still totally untested)

NB: it doesn't handle quotes in the middle of a quoted area, you can't escape quotes, you can't have more than one space.

**Comment by kashif** [comment]
@mosesn ah great I will try it out after dinner thank you!

**Comment by mosesn** [comment]
@kashif did you have a chance to try it?

**Comment by kashif** [comment]
@mosesn I seem to now get an error:

```
...
[error]         x EVAL
[error]           Unsupported command:  (Command.scala:270)
[error]           com.twitter.finagle.redis.protocol.Commands$$anonfun$doMatch$2.apply(Command.scala:270)
...
```

which might suggest that the parsing is now setting the `command` to just empty?

**Comment by mosesn** [comment]
Can you push your stuff to this branch so I can try it out myself?

**Comment by kashif** [comment]
all the stuff i have done till now is pushed here... I just added in your patch and tried to run the test:

```
$ ./sbt finagle-redis/test
...
```

**Comment by mosesn** [comment]
OK, I made a pull request against your branch.  I had confused the semantics of filter / filterNot.  It should be fine now.

https://github.com/kashif/finagle/pull/1

**Comment by kashif** [comment]
great that works! I will now add the rest of the `SCRIPT` commands

**Comment by mosesn** [comment]
@kashif howdy, do you need any help from me?

**Comment by luciferous** [comment]
@kashif How's this coming along? Anything we can do to assist?

**Comment by mosesn** [comment]
@kashif hey, I just wanted to check in.  Is this something you're still interested in working on?

**Comment by mosesn** [comment]
@kashif I think https://github.com/twitter/finagle/pull/383 solves the same problem, so I'm going to close this ticket once that merges in.  Thanks for your work on this PR–I'd be happy to work with you again in the future if you want to take another stab at a PR for finagle!

**Comment by roanta** [comment]
This landed in https://github.com/twitter/finagle/commit/18a8387e6c1157595c77447f9942e46fed39c8a3

**Pull request closed without merging**
