### PR TITLE
Migrate to build sbt

### PR DESCRIPTION
**Pull request by matsu-chara**
Problem:

Build trait was deprecated

Solution:

- step1: move project/Build.scala to build.sbt
- step2.1: remove Build trait
- step2.2: remove unnecessary import(sbt, Keys, and some plugins)
- step3: remove unnecessary settings
  - Defaults.coreDefaultSettings which is loaded by CorePlugin
  - JmhPlugin.projectSettings which is loaded by JmhPlugin

Result:
  Migration is completed

### CODE REVIEW

**Comment by mosesn** [comment]
wow, this is seriously cool!  thanks so much for tackling this.

**Comment by vkostyukov** [comment]
I think this is awesome! Thanks @matsu-chara!

**Comment by mosesn** [comment]
@matsu-chara this was merged internally, but because of an internal breaking API change, it's not safe to publish right now, so I'm going to leave this ticket open.  Thanks for your contribution!

**Comment by mosesn** [comment]
@matsu-chara this finally made it to github, thanks!  https://github.com/twitter/finagle/commit/0fd63b01b646a0a04147dedc4e7568ff1e0c9fb4

**Pull request closed without merging**
