### PR TITLE
finagle-redis: Fix discard transaction bug

### PR DESCRIPTION
**Pull request by hongikeam**
Problem

Send `MULTI` command when discard transaction.

Solution

Change command `MULTI` to `DISCARD`.

Result

Successfully transaction discarded.

### CODE REVIEW

**Comment by kevinoliver** [comment]
this certainly looks like a bug to me. is there a way that you've tested it?

**Comment by mosesn** [comment]
@hongikeam just wanted to ping you in case you missed Kevin's question.  also, do you mind updating the commit message to match the Problem / Solution / Result format?

**Comment by hongikeam** [comment]
@kevinoliver @mosesn 

sorry i've been busy :(
i send a transaction twice that will be failed.
and i'm monitoring in redis-cli.

current revision
* server logs
```
# first
ERRO [20180831-16:07:35.993] server-service: com.twitter.finagle.redis.ServerError: EXECABORT Transaction discarded because of previous errors.
ERRO [20180831-16:07:35.993] server-service:     at com.twitter.finagle.redis.BaseClient$$anonfun$doRequest$1.applyOrElse(Client.scala:103)
ERRO [20180831-16:07:35.993] server-service:     at com.twitter.finagle.redis.BaseClient$$anonfun$doRequest$1.applyOrElse(Client.scala:102)
...

# second
ERRO [20180831-16:08:48.371] server-service: com.twitter.finagle.redis.ServerError: ERR MULTI calls can not be nested
ERRO [20180831-16:08:48.371] server-service:     at com.twitter.finagle.redis.BaseClient$$anonfun$doRequest$1.applyOrElse(Client.scala:103)
ERRO [20180831-16:08:48.371] server-service:     at com.twitter.finagle.redis.BaseClient$$anonfun$doRequest$1.applyOrElse(Client.scala:102)
...
```

* redis logs
```
# first
1535699255.942261 [0 127.0.0.1:62377] "MULTI"
1535699255.947154 [0 127.0.0.1:62377] "EXEC"
1535699255.992372 [0 127.0.0.1:62377] "MULTI"
1535699255.992794 [0 127.0.0.1:62377] "MULTI"

# second
1535699328.371062 [0 127.0.0.1:62377] "MULTI"
```

my revision
```
# first
ERRO [20180831-16:17:25.102] server-service: com.twitter.finagle.redis.ServerError: EXECABORT Transaction discarded because of previous errors.
ERRO [20180831-16:17:25.102] server-service:     at com.twitter.finagle.redis.BaseClient$$anonfun$doRequest$1.applyOrElse(Client.scala:103)
ERRO [20180831-16:17:25.102] server-service:     at com.twitter.finagle.redis.BaseClient$$anonfun$doRequest$1.applyOrElse(Client.scala:102)

# second
ERRO [20180831-16:18:00.401] server-service: com.twitter.finagle.redis.ServerError: EXECABORT Transaction discarded because of previous errors.
ERRO [20180831-16:18:00.401] server-service:     at com.twitter.finagle.redis.BaseClient$$anonfun$doRequest$1.applyOrElse(Client.scala:103)
ERRO [20180831-16:18:00.401] server-service:     at com.twitter.finagle.redis.BaseClient$$anonfun$doRequest$1.applyOrElse(Client.scala:102)
```

```
# first
1535699845.092552 [0 127.0.0.1:64837] "MULTI"
1535699845.098164 [0 127.0.0.1:64837] "EXEC"
1535699845.101876 [0 127.0.0.1:64837] "DISCARD"
1535699845.102252 [0 127.0.0.1:64837] "DISCARD"

# second
1535699880.398286 [0 127.0.0.1:64837] "MULTI"
1535699880.399989 [0 127.0.0.1:64837] "EXEC"
1535699880.401317 [0 127.0.0.1:64837] "DISCARD"
1535699880.401612 [0 127.0.0.1:64837] "DISCARD"
```

if you looking previous commit (8months ago) then you'll get what is the problem.

**Comment by nepthar** [comment]
Thanks! This merged in 79c9cfd

**Pull request closed without merging**
