### PR TITLE
chore: Included githubactions in the dependabot config

### PR DESCRIPTION
**Pull request by nathannaveen**
This should help with keeping the GitHub actions updated on new releases. This will also help with keeping it secure.

Dependabot helps in keeping the supply chain secure https://docs.github.com/en/code-security/dependabot

GitHub actions up to date https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

https://github.com/ossf/scorecard/blob/main/docs/checks.md#dependency-update-tool
Signed-off-by: nathannaveen <42319948+nathannaveen@users.noreply.github.com>

### CODE REVIEW

**Comment by yufangong** [comment]
@nathannaveen Hi, can you please sign the CLA for this? Also, do you mind explaining what would be the result after this PR, will dependabot open PRs for upgrading dependencies?

**Comment by yufangong** [comment]
@nathannaveen Hi, can you please sign the CLA for this? Also, do you mind explaining what would be the result after this PR, will dependabot open PRs for upgrading dependencies?

**Comment by nathannaveen** [comment]
> @nathannaveen Hi, can you please sign the CLA for this? Also, do you mind explaining what would be the result after this PR, will dependabot open PRs for upgrading dependencies?

I have signed it, and yes it will open PRs for upgrades.

**Comment by jyanJing** [comment]
Hi @nathannaveen, thank you for adding dependabot to our repository! Since this involves detecting and resolving vulnerabilities for our project, we need to consult with our security group to understand the outcome a bit more. I am in touch with them and will keep you posted on the progress.

**Comment by jyanJing** [comment]
Hi @nathannaveen, we are already using a similar security tooling to scan and monitor our repositories. Based on the investigation, Dependabot performs the similar functionality. So we are leaning towards using the existing tooling. I am going to close this pr, please re-open if you feel strongly about adding Depandabot, thank you!

**Pull request closed without merging**
