### PR TITLE
Enable scala 2.13 on finagle-exp

### PR DESCRIPTION
**Pull request by DieBauer**
Problem

finagle-exp is not available for scala 2.13 

Solution

add 2.13 for this module in build.sbt

Result

Have scala 2.13 support for this module

### CODE REVIEW

**Comment by mosesn** [comment]
great, thanks for the PR @DieBauer!  did you test it locally on 2.13?  our travis-ci isn't set up to test against 2.13 yet unforch.

**Comment by DieBauer** [comment]
@mosesn yes I ran sbt with 2.13 and the tests for this specific module :) 


```sh
> curl -s https://raw.githubusercontent.com/twitter/dodo/develop/bin/build | bash -s -- --no-test finagle
> sbt
sbt:finagle> ++2.13.0
[info] Setting Scala version to 2.13.0 on 11 projects.
[info] Excluded 20 projects, run ++ 2.13.0 -v for more details.
[info] Reapplying settings...
[info] Using Netty SNAPSHOT build mode: false
[info] Netty version: 4.1.39.Final
[info] Netty tcnative version 2.0.25.Final
[info] Set current project to finagle (in build file:/Users/jens/Development/finagle/)
sbt:finagle> finagle-exp/test
...
...
lots of deprecation warnings from other finagle modules

[info] ScalaTest
[info] Run completed in 11 seconds, 400 milliseconds.
[info] Total number of tests run: 16
[info] Suites: completed 4, aborted 0
[info] Tests: succeeded 16, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[info] Passed: Total 16, Failed 0, Errors 0, Passed 16
[success] Total time: 41 s, completed Oct 3, 2019 9:07:19 PM

```

**Comment by DieBauer** [comment]
@mosesn can we enable 2.13 for travis? Or is there a blocker?

**Comment by mosesn** [comment]
@DieBauer the difficulty is that the scala version is enabled across the entire project, so we're planning on enabling 2.13 once everything is migrated to support it.  we could probably do it on a per-subproject basis, but I'm not sure it's worth investigating when we'll hopefully have finished soon.

**Comment by yufangong** [comment]
Thanks so much @DieBauer. Merged here https://github.com/twitter/finagle/commit/32bc9f48c3c4b99b3b847134ac315797bd80a643

**Pull request closed without merging**
