### PR TITLE
Adding Talenteca to the adopters page

### PR DESCRIPTION
**Pull request by csaltos**

### CODE REVIEW

**Comment by travisbrown** [comment]
Hi, @csaltos—it's great to see this, and thanks also for the examples you've been working on. I'll be pulling this internally today, but we'd also love to hear more about how you're using Finagle at Talenteca.

**Comment by mosesn** [comment]
:+1:

**Comment by travisbrown** [comment]
[Now](https://github.com/twitter/finagle/commit/9223c180c806eff83a9b56ae3f3fb86cc07c121c) in the `develop` branch.

**Comment by csaltos** [comment]
Hi @travisbrown and @mosesn thank you for your messages and support.

Two weeks ago we rolled out our first Finagle microservice at Talenteca. We decide to begin with a simple service like our URL shrinker tool (talenteca.com -> tltk.co), so we migrate from Spray/JSON to Finagle/Thrift and it's working amazingly great !! ... we are suporting 10 times more concurrent connections and the memory usage drops a lot too. The CPU usage increased but that's OK for us, actually we like to keep our CPUs hot, AWS does not charge us extra for CPU high usage !! ;) :)

Today, as I write you these lines our second Finagle microservice is being rolled out at Talenteca. We decide to migrate a more ambitious server and we choose our newsletter service to migrate, so we are migrating from Spray/JSON to Finagle/Thrift and this time we also are adding Finagle/Redis for the newsletter subscription/unsubscription features. Once again the performance improves a lot and beyond of that the code is very clean and straightforward, we love that, it's truly a joy.

Finagle is an excellent software and we decide to migrate all of our Spray/JSON services to Finagle/Thrift in these coming months and the new backend developments we have we are going to do it directly with Finagle.

I will let you know how is the roll out of today going, so wish us good luck !! ;) :)

Once again thanks for your support and for Finagle, thank you for sharing and make Finagle available Open Source.

**Pull request closed without merging**
