### PR TITLE
add scripting feature to finagle-redis with integration tests

### PR DESCRIPTION
**Pull request by timxzl**
currently supported commands: EVAL, EVALSHA, SCRIPT EXISTS, SCRIPT FLUSH, SCRIPT LOAD.

also contains fix for some unit tests that interfere with ExitGuardTest.

### CODE REVIEW

**Comment by jmoseley** [comment]
Is there any update for this PR?

**Comment by timxzl** [comment]
@jmoseley no updates since I last submitted. still waiting for some contributor to take a look and (possibly) merge it in.

**Comment by jmoseley** [comment]
OK thanks @timxzl

**Comment by kevinoliver** [comment]
Thanks for your patience. Our team doesn't have a lot of redis expertise, and thus the delay. It may still take some time until we get to it.

**Comment by timxzl** [comment]
thanks @kevinoliver! take your time, please. don't worry.

**Comment by mosesn** [comment]
@timxzl sorry it took so long for us to look at this.  it looks good to me!

**Comment by timxzl** [comment]
@mosesn thanks for taking care of it! Feel free to ping me if you want anything from my side.

**Comment by roanta** [comment]
Thanks for the patch @timxzl – it was merged: https://github.com/twitter/finagle/commit/18a8387e6c1157595c77447f9942e46fed39c8a3

**Comment by timxzl** [comment]
@roanta thanks! I have noticed that early this month. Glad to be of some service to the community!

**Pull request closed without merging**
