### PR TITLE
Add Brigade to adopters list

### PR DESCRIPTION
**Pull request by matteobanerjee**

### CODE REVIEW

**Comment by vkostyukov** [comment]
Thanks @matteobanerjee! That's really cool to see you use Finagle. Mind sharing some details on how do you use it?

**Comment by matteobanerjee** [comment]
Sure, we will probably write a blog post or two in the future.

For now I can say that the data/relevance team here at Brigade has adopted Finagle to implement its services, which are either computationally intensive (recommendations) or high volume (event logging). We expose them to a Ruby on Rails web app via Thrift.

**Comment by mosesn** [comment]
LGTM!

**Comment by vkostyukov** [comment]
I'm pulling this internally. Will close this PR once it's merged. Thanks @matteobanerjee!

**Comment by vkostyukov** [comment]
This was merged internally. Thanks again @matteobanerjee!

**Pull request closed without merging**
