### PR TITLE
finagle-stats: -> 2.13; finagle-stats-core: -> 2.13

### PR DESCRIPTION
**Pull request by hderms**
Problem

No cross-build for finagle-stats 2.13 and finagle-stats-core 2.13

Solution

include 2.13 in finagle-stats and finagle-stats-core cross versions.

### CODE REVIEW

**Comment by yufangong** [comment]
I think there are a few places in code that need change to compatible with scala 2.13.
Could you compile this against 2.13 to verify?

**Comment by hderms** [comment]
@yufangong Sorry about that I apparently didn't know how to trigger cross-compilation

**Comment by hderms** [comment]
@yufangong just to make sure I'm doing this properly, if it compiles with `sbt +compile` after having added 2.13 as a cross-compilation target (which this PR already does), then we are good to go from a compilation perspective?

**Comment by yufangong** [comment]
@hderms I think so! Maybe "./sbt +test:compile" just make sure all tests also good. Thanks!

**Comment by yufangong** [comment]
this is merged https://github.com/twitter/finagle/commit/4144d73c9e9f997e219e90888cce108861dc6046. Thanks!!!

**Pull request closed without merging**
