### PR TITLE
Adding link to configuring fault tolerant finagle clients

### PR DESCRIPTION
**Pull request by amartinsn**
I've had lots of positive feedbacks on this post and I would like to make it available on the website so new devs can have access to another resource.

### CODE REVIEW

**Comment by mosesn** [comment]
LGTM

**Comment by kevinoliver** [comment]
:ship:

**Comment by ryanoneill** [comment]
Hi @amartinsn, this has been submitted internally. We will close out the pull request when it's been pushed back to GitHub from our internal codebase. Thanks again.

**Comment by dschobel** [comment]
merged in 5dbcbd1b614de1b57c589404fef4e5d14cbfa4a8 

thanks @amartinsn

**Pull request closed without merging**
