### PR TITLE
Adding Hopper to Finagle adopters

### PR DESCRIPTION
**Pull request by n8han**
Hopper uses Finagle for almost all services and service clients, including its mobile app API.

### CODE REVIEW

**Comment by travisbrown** [comment]
Thanks @n8han!

**Comment by mosesn** [comment]
Aw man, I didn't know you had left NYC!  Well, I'm sure Montreal is happy to have you :+1: let us know if you have any questions about finagle, we're happy to help!  I'm looking forward to seeing you around.

**Comment by n8han** [comment]
Thanks guys, happy to be here (Montreal/Fingleland)!

**Comment by travisbrown** [comment]
I'm pulling this in to be merged.

**Comment by travisbrown** [comment]
Now [on GitHub](https://github.com/twitter/finagle/commit/677eb4477d55558ca040f4159761463c3a75e38d).

**Pull request closed without merging**
