### PR TITLE
Add Spright to Finagle adopters list

### PR DESCRIPTION
**Pull request by keeth**

### CODE REVIEW

**Comment by travisbrown** [comment]
Mind using HTTPS? Otherwise :+1:, thanks! (and for reference this is a follow-up to [this PR](https://github.com/finagle/finch/pull/225)).

**Comment by vkostyukov** [comment]
:+1:

**Comment by travisbrown** [comment]
I've pulled this internally, and it should be up with the sync on Monday.

**Comment by travisbrown** [comment]
Okay, this is merged internally and I'll close this PR with the next sync to the `develop` branch. Thanks again @keeth!

**Comment by travisbrown** [comment]
Now [on GitHub](https://github.com/twitter/finagle/commit/96450e4e499868aa00067e4f695f3b8a4e827871)—thanks!

**Comment by keeth** [comment]
Awesome, thanks guys! :metal:

**Pull request closed without merging**
