### PR TITLE
finagle-http: Implement streaming disconnection tests

### PR DESCRIPTION
**Pull request by olix0r**
Problem

finagle-http's streaming test coverage misses some important cases

Solution

Introduce new tests to http.StreamingTest to validate that

1. A client behaves well when a connection is lost before a server responds.
2. A server closes the transport after responding, as described in twitter/finagle#475.

### CODE REVIEW

**Comment by olix0r** [comment]
cc @mosesn

**Comment by mosesn** [comment]
Does this need the two patches I added here: https://github.com/mosesn/finagle/commits/mnakamura/test-streaming-disconnects ?

**Comment by olix0r** [comment]
@mosesn indeed it does...

**Comment by olix0r** [comment]
This branch _looks_ right to me, but it fails (which either means there's still a bug or the tests are bad...)

```
[info] StreamingTest:
[info] - client: request stream fails on write *** FAILED ***
[info]   com.twitter.finagle.ChannelWriteException: com.twitter.finagle.ChannelClosedException: null at remote address: /0.0.0.0:62345. Remote Info: Not Available from service: client. Remote Info: Upstream Address: Not Available, Upstream Client Id: Not Available, Downstream Address: /0.0.0.0:62345, Downstream Client Id: client, Trace Id: bbee79fcb6d28fea.bbee79fcb6d28fea<:bbee79fcb6d28fea
[info]   at com.twitter.finagle.NoStacktrace(Unknown Source)
[info]   ...
[info]   Cause: com.twitter.finagle.ChannelClosedException: null at remote address: /0.0.0.0:62345. Remote Info: Not Available
[info]   at com.twitter.finagle.NoStacktrace(Unknown Source)
[info]   ...
[info]   Cause: java.nio.channels.ClosedChannelException:
[info]   at org.jboss.netty.channel.socket.nio.AbstractNioWorker.cleanUpWriteBuffer(AbstractNioWorker.java:433)
[info]   at org.jboss.netty.channel.socket.nio.AbstractNioWorker.writeFromUserCode(AbstractNioWorker.java:128)
[info]   at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:84)
[info]   at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:779)
[info]   at org.jboss.netty.channel.SimpleChannelHandler.writeRequested(SimpleChannelHandler.java:292)
[info]   at org.jboss.netty.channel.SimpleChannelHandler.handleDownstream(SimpleChannelHandler.java:254)
[info]   at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
[info]   at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784)
[info]   at org.jboss.netty.channel.SimpleChannelHandler.writeRequested(SimpleChannelHandler.java:292)
[info]   at org.jboss.netty.channel.SimpleChannelHandler.handleDownstream(SimpleChannelHandler.java:254)
[info]   ...
[info] - client: response stream fails on read *** FAILED ***
[info]   com.twitter.finagle.ChannelWriteException: com.twitter.finagle.ChannelClosedException: null at remote address: /0.0.0.0:62347. Remote Info: Not Available from service: client. Remote Info: Upstream Address: Not Available, Upstream Client Id: Not Available, Downstream Address: /0.0.0.0:62347, Downstream Client Id: client, Trace Id: bbee79fcb6d28fea.bbee79fcb6d28fea<:bbee79fcb6d28fea
[info]   at com.twitter.finagle.NoStacktrace(Unknown Source)
[info]   ...
[info]   Cause: com.twitter.finagle.ChannelClosedException: null at remote address: /0.0.0.0:62347. Remote Info: Not Available
[info]   at com.twitter.finagle.NoStacktrace(Unknown Source)
[info]   ...
[info]   Cause: java.nio.channels.ClosedChannelException:
[info]   at org.jboss.netty.channel.socket.nio.AbstractNioWorker.cleanUpWriteBuffer(AbstractNioWorker.java:433)
[info]   at org.jboss.netty.channel.socket.nio.AbstractNioWorker.writeFromUserCode(AbstractNioWorker.java:128)
[info]   at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:84)
[info]   at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:779)
[info]   at org.jboss.netty.channel.SimpleChannelHandler.writeRequested(SimpleChannelHandler.java:292)
[info]   at org.jboss.netty.channel.SimpleChannelHandler.handleDownstream(SimpleChannelHandler.java:254)
[info]   at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
[info]   at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784)
[info]   at org.jboss.netty.channel.SimpleChannelHandler.writeRequested(SimpleChannelHandler.java:292)
[info]   at org.jboss.netty.channel.SimpleChannelHandler.handleDownstream(SimpleChannelHandler.java:254)
[info]   ...
[info] - client: server disconnect on pending response should fail request
[info] - client: client closes transport after server disconnects
[info] - client: fail request writer *** FAILED ***
[info]   $anon.this.res2.isDefined was true (StreamingTest.scala:146)
[info] - client: discard respond reader *** FAILED ***
[info]   com.twitter.finagle.ChannelWriteException: com.twitter.finagle.ChannelClosedException: null at remote address: /0.0.0.0:62553. Remote Info: Not Available from service: client. Remote Info: Upstream Address: Not Available, Upstream Client Id: Not Available, Downstream Address: /0.0.0.0:62553, Downstream Client Id: client, Trace Id: bbee79fcb6d28fea.bbee79fcb6d28fea<:bbee79fcb6d28fea
[info]   at com.twitter.finagle.NoStacktrace(Unknown Source)
[info]   ...
[info]   Cause: com.twitter.finagle.ChannelClosedException: null at remote address: /0.0.0.0:62553. Remote Info: Not Available
[info]   at com.twitter.finagle.NoStacktrace(Unknown Source)
[info]   ...
[info]   Cause: java.nio.channels.ClosedChannelException:
[info]   at org.jboss.netty.channel.socket.nio.AbstractNioWorker.cleanUpWriteBuffer(AbstractNioWorker.java:433)
[info]   at org.jboss.netty.channel.socket.nio.AbstractNioWorker.writeFromUserCode(AbstractNioWorker.java:128)
[info]   at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:84)
[info]   at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:779)
[info]   at org.jboss.netty.channel.SimpleChannelHandler.writeRequested(SimpleChannelHandler.java:292)
[info]   at org.jboss.netty.channel.SimpleChannelHandler.handleDownstream(SimpleChannelHandler.java:254)
[info]   at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
[info]   at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784)
[info]   at org.jboss.netty.channel.SimpleChannelHandler.writeRequested(SimpleChannelHandler.java:292)
[info]   at org.jboss.netty.channel.SimpleChannelHandler.handleDownstream(SimpleChannelHandler.java:254)
[info]   ...
[info] - server: request stream fails read
[info] - server: response stream fails write
[info] - server: fail response writer
[info] - server: fail request reader
[info] - end-to-end: client may process multiple streaming requests simultaneously
[info] ScalaTest
[info] Run completed in 3 seconds, 443 milliseconds.
[info] Total number of tests run: 11
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 7, failed 4, canceled 0, ignored 0, pending 0
[info] *** 4 TESTS FAILED ***
```

**Comment by olix0r** [comment]
https://github.com/twitter/finagle/pull/487/commits/61f193a62d9154377d40c6fe6da1659a0132dca2 appears to break these tests.

Specifically, the following:
```scala
  def connect(addr: SocketAddress, mod: Modifier, name: String = "client") = {
    val fac = ClientBuilder()
      .codec(new Custom(mod, identity))
      .hosts(Seq(addr.asInstanceOf[InetSocketAddress]))
      .hostConnectionLimit(1)
      .name(name)
      .buildFactory()
    await(fac()
  }
```
This obtains a single connection such that when the transport fails, subsequent requests fail.

Tests pass when this is changed to:
```scala
  def connect(addr: SocketAddress, mod: Modifier, name: String = "client") =
    ClientBuilder()
      .codec(new Custom(mod, identity))
      .hosts(Seq(addr.asInstanceOf[InetSocketAddress]))
      .hostConnectionLimit(1)
      .name(name)
      .build()
```

**Comment by mosesn** [comment]
@olix0r that patch seems to be nonsense.  I don't understand it, or why either of us thought it was a good idea (you seem to have merged it in here: https://github.com/BuoyantIO/finagle/pull/3/files.  Trying to find the original on my hard drive in case github did something funny here.

**Comment by mosesn** [comment]
Nope, github is correct, that commit is just a bunch of nonsense.  I'll try to figure out what I was thinking about again.

**Comment by mosesn** [comment]
OK I just have no idea what that commit was supposed to do, but I think the test might not be right now that I'm thinking about it.  If the client succeeds in writing all of its bytes to the wire, it won't realize that the remote has closed the connection until it next tries to write over the connection, so that test is inherently racy.

**Comment by olix0r** [comment]
Yep, the _client: server disconnect on pending response should fail request_ test times out because the response is never triggered.  I could change this to attempt a write after its closed, but maybe that test isn't particularly useful.

**Comment by mosesn** [comment]
The good news is that I figured out what that patch was supposed to do!  The `FactoryToService`'d client is lazy, so it hasn't tried to establish a connection on creation.  My concern was that when we made a request, we could still be establishing a connection when we cut the connection.

**Comment by mosesn** [comment]
@olix0r it seems like adding a promise that you satisfy when the request has been received, and awaiting that promise also fixes the test.

**Comment by mosesn** [comment]
OK, now that I think about it more, I'm confused.  Why does this fix it?  Why would the server never receiving the request mean that we should time out?

**Comment by olix0r** [comment]
@mosesn is it because the `read()` fails on the response?

I've changed it as follows and the test now passes:
```scala

  test("client: server disconnect on pending response should fail request") {
    val failure = new Promise[Unit]
    val service = Service.mk[Request, Response] { req =>
      failure.setDone()
      Future.never
    }
    val server = startServer(service, closingTransport(failure))
    val client = connect(server.boundAddress, identity)

    val resF = client(get("/"))
    intercept[ChannelClosedException] { await(resF) }

    await(client.close())
    await(server.close())
  }
```

**Comment by olix0r** [comment]
@mosesn but now i'm confused -- how is this at all functionally different than:

```scala
  test("client: server disconnect on pending response should fail request") {
    val failure = new Promise[Unit]
    val service = Service.mk[Request, Response] { req =>
      Future.never
    }
    val server = startServer(service, closingTransport(failure))
    val client = connect(server.boundAddress, identity)

    val resF = client(get("/"))
    failure.setDone()
    intercept[ChannelClosedException] { await(resF) }

    await(client.close())
    await(server.close())
  }
```

I assume that _failure_ is being satisfied before the server processes the request -- why does this timeout but the other mode, where the server fully receives the request, fails?

**Comment by mosesn** [comment]
OK, so thinking about it more (and adding a bunch of printlns), I think that the problem is that the client says it has successfully established a connection when the kernel finishes the handshake, and the server might not have called accept and assigned a transport yet.  So there's a race between `failure` being set to done and calling the modifier we pass to the `startServer`.

The smallest diff I've found that can fix the test is removing the `if (failure.isDefined)` which seems pretty compelling.

**Comment by mosesn** [comment]
Thaaaaaaanks @olix0r

**Comment by mosesn** [comment]
Made it to `develop` here: https://github.com/twitter/finagle/commit/4488767656c64e6ad67c4eff4099739c18579b2d thanks!

**Pull request closed without merging**
