### PR TITLE
Update ADOPTERS.md

### PR DESCRIPTION
**Pull request by ryanb93**
Adding Hotels.com to list of Finagle adopters.

### CODE REVIEW

**Comment by vkostyukov** [comment]
Thanks for letting us know, @ryanb93! Any chance you can share just a little bit of details on how you use Finagle (protocols, versions, etc)? We'd extremally appreciate it.

**Comment by ryanb93** [comment]
@vkostyukov we are currently using version 2.11.0 of finatra-http_2.12 as a HTTP client to send requests between services. We're taking advantage of the built in circuit breaker as a replacement for [Hystrix](https://github.com/Netflix/Hystrix), that we would usually use.

**Comment by vkostyukov** [comment]
Thanks, @ryanb93! You might consider opening a similar PR against Finatra as well.

**Comment by ryanoneill** [comment]
Thanks @ryanb93, I will pull this in.

**Comment by vkostyukov** [comment]
This is merged in b4e73eef3d93487284173a4f884e06c307ff1749. Thanks @ryanb93!

**Pull request closed without merging**
