### PR TITLE
Upgrade Netty4 to version 4.1.3.Final

### PR DESCRIPTION
**Pull request by olix0r**
Problem

There are necessary improvements to Http2 codecs in Netty-4.1.3

Solution

Upgrade Netty!  Note that Netty's `OneTimeTask` utility has been removed. All
uses internal to Netty have been replaced with `Runnable`.

### CODE REVIEW

**Comment by mosesn** [comment]
LGTM, what's the main improvement here?

**Comment by olix0r** [comment]
There are a [number of minor improvements to flow control](http://netty.io/news/2016/07/01/4-0-38-Final-4-1-2-Final.html), but I'm especially interested in picking up https://github.com/netty/netty/pull/5324.

**Comment by taylorleese** [comment]
We're going to want the SSL changes as well (https://github.com/netty/netty/pull/5439 and https://github.com/netty/netty/pull/5380). /cc @ryanoneill

**Comment by olix0r** [comment]
It looks like 4.1.3.Final is being released today, which has another [fix](https://github.com/netty/netty/pull/5531) that I need.  Should I update this PR with 4.1.3? Submit another PR?

**Comment by mosesn** [comment]
If you could update this one that would be rad

**Comment by mosesn** [comment]
@olix0r I'm on guru duty this week, so I'm going to take a stab at doing the upgrade.  will keep you posted.

**Comment by mosesn** [comment]
@olix0r this was merged internally, but we just missed the boat on the github sync.  might do another one later this week.  thanks!

**Comment by mosesn** [comment]
This made it to `develop` here: https://github.com/twitter/finagle/commit/f320909985c5756eb48d612d99abaed939765066  thanks for the contribution!

**Pull request closed without merging**
