### PR TITLE
Adding Globo.com to the list of adopters.

### PR DESCRIPTION
**Pull request by amartinsn**

### CODE REVIEW

**Comment by travisbrown** [comment]
Some additional context [from the Finch room](https://gitter.im/finagle/finch?at=5615954bce6e633c4518eb6f):

> We are using Finch on video streaming platform
> we implemented a service that returns live transmission details based on users location

Thanks, @amartinsn!

**Comment by vkostyukov** [comment]
:+1: 

Thank you @amartinsn!

**Comment by travisbrown** [comment]
I'm pulling this in to be merged—should be up on Monday.

**Comment by mosesn** [comment]
LGTM

**Comment by amartinsn** [comment]
Nice!

**Comment by travisbrown** [comment]
[Merged](https://github.com/twitter/finagle/commit/490f6f8e88dab2486c7f584659ca118f68c6f872)—thanks again!

**Pull request closed without merging**
